### PR TITLE
Jcf1991 dev

### PR DESCRIPTION
**Pull request by jcf1991**
I suggest we bring all of the recent changes on various branches into master. I've pulled them all into my own branch, so y'all can pull from that in the meantime. The only thing I commented out was Landan's admin authentication popup getting invoked, I just set self.admin to True and left a comment explaining that the popup didn't properly close itself on my system (I wasn't sure if this was a Mac/Linux difference or if that code wasn't really done yet). Everything else should be a pretty seamless incorporation of the changes in all branches.

### CODE REVIEW

**Review by lgint8042 — COMMENTED** [review]
I'm confused what the .pyc file is and why it is here? Also you marked two tasks done on US16 about writing into an external text file but I don't see any changes for that here? It still looks like its all using the database, so I unchecked those on Trello. I think that everything else looks good though.

**Comment by lgint8042** [comment]
Fixed the issue of the system not being able to detect blinks properly.

**Review by Danielle333 — COMMENTED** [review]
The popup asking if you're an admin or user works on my laptop. Is this possibly just a Linux issue? 

In addition to what Landan said, I thought the majority of the group voted to use an external file to save data instead of a database.

**Review by codieorberson — APPROVED** [review]
Looks good to me. But you can take out that last file that you added from my branch, the test.py file. I had that to just see an example of how someone stores information in a listbox.

**Pull request merged**
